import { useState } from "react";
import { KeyRound, LoaderCircle, ShieldCheck } from "lucide-react";
import { exportLocalData, importLocalData } from "../lib";
import type { ProviderConfig } from "../types";
import { ConfirmClearModal } from "../components/ConfirmClearModal";

export function SettingsView(props: { provider: ProviderConfig; setProvider: (value: ProviderConfig) => void; apiKeyDraft: string; setApiKeyDraft: (value: string) => void; saveProvider: () => void; saving: boolean; message: string; clearClipboard: boolean; setClearClipboard: (value: boolean) => void; monthlyWarningLimit: number; setMonthlyWarningLimit: (value: number) => void; monthlyLimit: number; setMonthlyLimit: (value: number) => void; onClearData: () => Promise<void> }) {
  const { provider, setProvider, apiKeyDraft, setApiKeyDraft, saveProvider, saving, message, clearClipboard, setClearClipboard, monthlyWarningLimit, setMonthlyWarningLimit, monthlyLimit, setMonthlyLimit, onClearData } = props;
  const [confirmClear, setConfirmClear] = useState(false);
  const [dataMessage, setDataMessage] = useState("");
  return <main className="page"><header className="page-header"><div><h1>设置</h1><p>供应商、费用、隐私和本地数据</p></div></header>
    <section className="settings-section"><div className="settings-heading"><div><h2><KeyRound size={18} />DeepSeek 供应商</h2><p>API Key 将存入 Windows 凭据管理器。</p></div><span className={`connection ${provider.hasApiKey ? "ok" : ""}`}>{provider.hasApiKey ? "已配置" : "未配置"}</span></div>
      <div className="form-grid"><label>API Base URL<input value={provider.baseUrl} onChange={(event) => setProvider({ ...provider, baseUrl: event.target.value })} /></label><label>API Key<input type="password" value={apiKeyDraft} onChange={(event) => setApiKeyDraft(event.target.value)} placeholder={provider.hasApiKey ? "已保存，留空表示不修改" : "sk-..."} /></label><label>V4-Flash 模型 ID<input value={provider.v4FlashModelId} onChange={(event) => setProvider({ ...provider, v4FlashModelId: event.target.value })} placeholder="deepseek-v4-flash" /></label><label>默认模型<select value={provider.defaultModel} onChange={(event) => setProvider({ ...provider, defaultModel: event.target.value })}><option value="deepseek-chat">deepseek-chat</option><option value="v4-flash" disabled={!provider.v4FlashModelId}>V4-Flash</option></select></label></div>
      <div className="settings-actions">{message && <span>{message}</span>}<button className="primary" onClick={saveProvider} disabled={saving}>{saving ? <LoaderCircle className="spin" size={16} /> : <ShieldCheck size={16} />}验证并保存</button></div>
    </section>
    <section className="settings-section"><div className="settings-heading"><div><h2>费用控制</h2><p>按本机记录估算；供应商账单仍是最终依据。设为 0 表示关闭对应额度。</p></div></div><div className="form-grid"><label>月度提醒额度（元）<input type="number" min="0" step="1" value={monthlyWarningLimit} onChange={(event) => setMonthlyWarningLimit(Number(event.target.value))} /></label><label>月度强制额度（元）<input type="number" min="0" step="1" value={monthlyLimit} onChange={(event) => setMonthlyLimit(Number(event.target.value))} /></label><label>输入价格（元/千 token）<input type="number" min="0" step="0.0001" value={provider.inputPrice} onChange={(event) => setProvider({ ...provider, inputPrice: Number(event.target.value) })} /></label><label>输出价格（元/千 token）<input type="number" min="0" step="0.0001" value={provider.outputPrice} onChange={(event) => setProvider({ ...provider, outputPrice: Number(event.target.value) })} /></label></div></section>
    <section className="settings-section"><div className="settings-heading"><div><h2>剪贴板与隐私</h2><p>软件不收集遥测，不上传崩溃报告。</p></div></div><label className="setting-row"><div><strong>2 分钟后清理本软件复制的内容</strong><span>只有剪贴板仍是本软件写入的内容时才会清理。</span></div><label className="toggle"><input type="checkbox" checked={clearClipboard} onChange={(event) => setClearClipboard(event.target.checked)} /><span /></label></label><div className="setting-row"><div><strong>历史保留 90 天，最大 500 MB</strong><span>附件原件不保存；导出包不包含 API Key、附件原件或操作日志。</span>{dataMessage && <span>{dataMessage}</span>}</div><div className="inline-actions"><button className="secondary" onClick={async () => { try { const exported = await exportLocalData(); if (exported) setDataMessage(`已导出 ${exported.records} 条记录：${exported.path}`); } catch (cause) { setDataMessage(cause instanceof Error ? cause.message : String(cause)); } }}>导出数据</button><button className="secondary" onClick={async () => { try { const imported = await importLocalData(); if (imported) setDataMessage(`已导入 ${imported.records} 条记录；重新打开历史页面即可查看。`); } catch (cause) { setDataMessage(cause instanceof Error ? cause.message : String(cause)); } }}>导入数据</button><button className="secondary danger-outline" onClick={() => setConfirmClear(true)}>清空全部本地数据</button></div></div></section>
    {confirmClear && <ConfirmClearModal onCancel={() => setConfirmClear(false)} onConfirm={async () => { await onClearData(); setConfirmClear(false); }} />}
  </main>;
}
